services:
  HeimrichHannot\FrontendFrameworkBundle\:
    resource: '../src/{DataContainer}/*'
    autoconfigure: true
    autowire: true

  HeimrichHannot\FrontendFrameworkBundle\Helper\FrontendFrameworkHelper:
    autowire: true
    public: true